"""empty message

Revision ID: 51e8c432ffef
Revises: 7f87e1ba40b8
Create Date: 2022-05-12 21:12:28.682716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51e8c432ffef'
down_revision = '7f87e1ba40b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('descricao', sa.Text(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('links', 'descricao')
    # ### end Alembic commands ###
